Update to 0.7.0 for standard deployment scripts and templates
solliancenet/foundationallm pull request #1125
Opened 2024-06-05 14:58 UTC by hatboyzero

# Update to 0.7.0 for standard deployment scripts and templates

2024-06-11 14:57 UTC, jamesrcounts requested changes

2024-06-11 14:57 UTC, jamesrcounts commented on deploy/common/helm/chat-ui/templates/deployment.yaml
> +          command: ["node", ".output/server/index.mjs"]
Matt you mentioned this might need to be removed

2024-06-11 14:57 UTC, jamesrcounts commented on deploy/common/helm/management-ui/templates/deployment.yaml
> +          command: ["node", ".output/server/index.mjs"]
Another item to review for remove

2024-06-11 14:57 UTC, jamesrcounts commented on deploy/quick-start/config/appconfig.template.json
> +    {
Has this change to quick-start been tested?

2024-06-11 14:57 UTC, jamesrcounts commented on deploy/standard/bicep/modules/eventgrid.bicep
> +// @description('Private endpoint for the resource')
Clean up comment

2024-06-11 14:57 UTC, jamesrcounts commented on deploy/standard/scripts/Deploy.ps1
> +    # Invoke-AndRequireSuccess "Uploading Auth Store Data" {
Clean up comments

2024-06-11 14:57 UTC, jamesrcounts commented on deploy/standard/scripts/Pre-Deploy.ps1
> +    Push-Location ./pre-provision
don't push into new dir

2024-06-11 14:57 UTC, jamesrcounts commented on deploy/standard/scripts/Pre-Deploy.ps1
> +            ./Bootstrap.ps1
Rename bootstrap no get-azcopy (or similar)

2024-06-11 14:57 UTC, jamesrcounts commented on deploy/standard/scripts/deploy/Deploy-Backend-Aks.ps1
> +# TODO: review helm settings these are set for internal registry
Cleanup comment

2024-06-11 14:57 UTC, jamesrcounts commented on deploy/standard/scripts/deploy/Generate-Config.ps1
> +# $tokens.vectorizationApiEntraClientId = $entraClientIds.vectorizationapi
cleanup comments

2024-06-11 14:57 UTC, jamesrcounts commented on deploy/standard/scripts/deploy/Upload-AuthStoreData.ps1
> +# Invoke-AndRequireSuccess "Uploading Default Role Assignments to Authorization Store" {
cleanup comments

2024-06-11 14:57 UTC, jamesrcounts commented on deploy/standard/scripts/deploy/Upload-SystemPrompts.ps1
> +# Invoke-AndRequireSuccess "Uploading Resource Providers" {
Clean up comment

2024-06-11 14:57 UTC, jamesrcounts commented on deploy/standard/scripts/pre-provision/Create-FllmAdminGroup.ps1
> +    $createGroupCommand = "az ad group create --display-name $groupName --mail-nickname $groupName"
check LASTEXITCODE for nonzero value and throw if needed

2024-06-11 14:57 UTC, jamesrcounts commented on deploy/standard/scripts/pre-provision/foundationalllm-authorization.json
> +{
remove generated file

2024-06-11 14:57 UTC, jamesrcounts commented on deploy/standard/scripts/pre-provision/foundationalllm-client.json
> +{
remove generated file

2024-06-11 14:57 UTC, jamesrcounts commented on deploy/standard/scripts/pre-provision/foundationalllm-management.json
> +{
remove

2024-06-11 14:57 UTC, jamesrcounts commented on deploy/standard/scripts/pre-provision/foundationalllm-managementclient.json
> +{
remove

2024-06-11 14:57 UTC, jamesrcounts commented on deploy/standard/scripts/pre-provision/foundationalllm.json
> +{
remove

2024-06-11 15:22 UTC, jamesrcounts requested changes

2024-06-11 15:22 UTC, jamesrcounts commented on deploy/standard/scripts/Deploy.ps1
> -    Pop-Location
We still need this pop

2024-06-11 15:26 UTC, jamesrcounts commented on deploy/standard/scripts/pre-provision/Create-FllmAdminGroup.ps1
> +    $createGroupCommand = "az ad group create --display-name $groupName --mail-nickname $groupName"
We can defer this

2024-06-11 15:33 UTC, hatboyzero commented on deploy/quick-start/config/appconfig.template.json
> +    {
Testing in progress right now.

2024-06-11 19:56 UTC, jamesrcounts approved these changes

2024-06-12 07:50 UTC, ciprianjichici approved these changes

2024-06-12 07:50 UTC, merged