Cherry picked updates to standard deployment from 0.7.0 PR #1125 into main
solliancenet/foundationallm pull request #1138
Opened 2024-06-11 13:57 UTC by hatboyzero

# Cherry picked updates to standard deployment from 0.7.0 PR #1125 into main

## Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have included inline docs for my changes, where applicable
- [ ]  I have successfully run a local build
- [ ]  I have provided the required update scripts, where applicable
- [ ]  I have updated relevant docs, where applicable

2024-06-11 14:58 UTC, jamesrcounts requested changes
please redo after updating #1125

2024-06-12 07:51 UTC, ciprianjichici approved these changes

2024-06-12 07:52 UTC, ciprianjichici approved these changes

2024-06-12 14:42 UTC, jamesrcounts approved these changes

2024-06-12 17:31 UTC, merged