Added support for parameterizing resources for ACA QS
solliancenet/foundationallm pull request #1166
Opened 2024-06-20 21:19 UTC by saimachi

# Added support for parameterizing resources for ACA QS

## The issue or feature being addressed

Currently, there is no way to specify ACA CPU and memory allocation and scaling policy. This is needed for Load Testing.

## Details on the issue fix or feature implementation

This PR adds AZD config keys with default values for scaling specific services at deploy time.

## Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have included inline docs for my changes, where applicable
- [ ]  I have successfully run a local build
- [ ]  I have provided the required update scripts, where applicable
- [ ]  I have updated relevant docs, where applicable

> [!NOTE]
> Instead of adding `X`'s inside the checkboxes you wish to check above, first submit the PR, then check the boxes in the rendered description.

2024-06-25 21:52 UTC, hatboyzero requested changes

2024-06-25 21:52 UTC, hatboyzero commented on deploy/quick-start/infra/main.parameters.json
> +          "replicaCount": "${SERVICE_AUTHORIZATIONAPI_REPLICAS}"
Can we specify a default number of replicas for each service?

2024-06-26 12:14 UTC, saimachi commented on deploy/quick-start/infra/main.parameters.json
> +          "replicaCount": "${SERVICE_AUTHORIZATIONAPI_REPLICAS}"
@hatboyzero If this value is null, it will use the default scaling policy from 1 to 10.

2024-06-26 12:15 UTC, saimachi commented on deploy/quick-start/infra/main.parameters.json
> +          "replicaCount": "${SERVICE_AUTHORIZATIONAPI_REPLICAS}"
![image](https://github.com/solliancenet/foundationallm/assets/37318129/53ac83e9-96e4-40b3-a654-b2e1a82135ed)

2024-06-26 12:49 UTC, hatboyzero approved these changes

2024-06-26 12:57 UTC, ciprianjichici approved these changes

2024-06-26 12:57 UTC, merged