Adding support for BYO OpenAI to Standard deployment
solliancenet/foundationallm pull request #1207
Opened 2024-07-03 17:33 UTC by hatboyzero

# Adding support for BYO OpenAI to Standard deployment

## The issue or feature being addressed

Fixes #17318

## Details on the issue fix or feature implementation

Updates bicep templates and automation scripts to add support for BYO OpenAI.

## Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have included inline docs for my changes, where applicable
- [ ]  I have successfully run a local build
- [ ]  I have provided the required update scripts, where applicable
- [ ]  I have updated relevant docs, where applicable

2024-07-03 17:58 UTC, jamesrcounts requested changes

2024-07-03 17:58 UTC, jamesrcounts commented on deploy/standard/bicep/main.bicep
> +param deployOpenAi bool = true
This should be a var and not part of the public interface

2024-07-03 17:58 UTC, jamesrcounts commented on deploy/standard/bicep/psakefile.ps1
> +        deployOpenAi                = @{
see the pattern for external DNS and external network below

2024-07-08 15:37 UTC, hatboyzero commented on deploy/standard/bicep/main.bicep
> +param deployOpenAi bool = true
Updated.

2024-07-08 15:37 UTC, hatboyzero commented on deploy/standard/bicep/psakefile.ps1
> +        deployOpenAi                = @{
Updated.

2024-07-08 16:39 UTC, jamesrcounts approved these changes

2024-07-08 17:47 UTC, jamesrcounts approved these changes

2024-07-12 19:36 UTC, ciprianjichici approved these changes

2024-07-12 19:36 UTC, merged