Support for deleting App Config keys
solliancenet/foundationallm pull request #1235
Opened 2024-07-16 13:29 UTC by saimachi

# Support for deleting App Config keys

## The issue or feature being addressed

Currently, Management API does not provide facilities to delete App Config keys.

## Details on the issue fix or feature implementation

This PR updates the Configuration Resource Provider and the Azure App Configuration Service to delete App Config keys and associated Key Vault secrets.

## Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have included inline docs for my changes, where applicable
- [ ]  I have successfully run a local build
- [ ]  I have provided the required update scripts, where applicable
- [ ]  I have updated relevant docs, where applicable

> [!NOTE]
> Instead of adding `X`'s inside the checkboxes you wish to check above, first submit the PR, then check the boxes in the rendered description.

2024-07-16 14:12 UTC, codingbandit requested changes

2024-07-16 14:12 UTC, codingbandit commented on src/dotnet/Common/Services/AzureAppConfigurationService.cs
The exception thrown should be a ResourceProviderException

2024-07-16 18:34 UTC, ciprianjichici commented on src/dotnet/Common/Services/AzureAppConfigurationService.cs
This is technically not a resource provider...

2024-07-17 13:32 UTC, codingbandit approved these changes

2024-07-17 19:21 UTC, ciprianjichici approved these changes

2024-07-17 19:21 UTC, merged