Add Standard Hub Network deployment
solliancenet/foundationallm pull request #1268
Opened 2024-07-24 21:53 UTC by deltadan

# Add Standard Hub network deployment

## New Standard Hub Network deployment to allow for separation between FLLM Standard Network and Hybrid Networking at Enterprise Clients. Will only be used if client doesn't have a Hub Network available to connect to FLLM Standard Network.

## Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have included inline docs for my changes, where applicable
- [ ]  I have successfully run a local build
- [ ]  I have provided the required update scripts, where applicable
- [ ]  I have updated relevant docs, where applicable

> [!NOTE]
> Instead of adding `X`'s inside the checkboxes you wish to check above, first submit the PR, then check the boxes in the rendered description.

2024-07-24 22:21 UTC, jamesrcounts requested changes

2024-07-24 22:21 UTC, jamesrcounts commented on deploy/standard-hub/azd-hooks/postprovision.ps1
> +$outputFolderPath = "../standard-hub/config/vpn"
Resolve to absolute path you can use the function that we use in some of the other scripts https://github.com/solliancenet/foundationallm/blob/9dbf36a23017241deefb2aeca2c3becb9cab7a49/deploy/common/scripts/Get-TestSettings.ps1#L32

2024-07-24 22:21 UTC, jamesrcounts commented on deploy/standard-hub/azd-hooks/postprovision.ps1
> +$outputFilePath = "$outputFolderPath/VpnClientConfiguration.zip"
use powershell's `Join-Path` cmdlet

2024-07-24 22:21 UTC, jamesrcounts commented on deploy/standard-hub/azd-hooks/postprovision.ps1
> +$vpnGatewayName = "vpng-${env:AZURE_ENV_NAME}-${env:AZURE_LOCATION}-net-${env:FLLM_PROJECT}"
For vpgGatewayName and resourceGroupName, can we use outputs from the bicep instead of recalculating the name?  It will be more reliable if we ever change or customize the naming convention.

2024-07-24 22:21 UTC, jamesrcounts commented on deploy/standard-hub/azd-hooks/postprovision.ps1
> +$vpnClientPackageUrl = az network vnet-gateway vpn-client generate `
add `--output tsv` to this cli call

2024-07-24 22:21 UTC, jamesrcounts commented on deploy/standard-hub/azd-hooks/postprovision.ps1
> +$vpnClientPackageUrl = $vpnClientPackageUrl -replace '"', ''
When you use tab-separated values (as suggested above), the output won't has quotes, and you won't need this line.

2024-07-24 22:21 UTC, jamesrcounts commented on deploy/standard-hub/azd-hooks/postprovision.ps1
> +# Assuming the XML file is directly inside the expanded folder
This looks like a duplicate of lines 33-35, am i missing a difference?

2024-07-24 22:21 UTC, jamesrcounts commented on deploy/standard-hub/infra/core/networking/dnsResolver.bicep
> +func namer(resourceAbbr string, env string, region string, workloadName string, projectId string) string =>
Consider moving the namer to a shared library file https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-import#example

2024-07-24 22:21 UTC, jamesrcounts commented on deploy/standard-hub/infra/main.bicep
> +module vpn './core/networking/vpnGateway.bicep' = if (createVpnGateway) {
Remove the condition.  The purpose of the template is to create this gateway.  Customers who do not want this gateway should not use this template.

2024-07-25 19:12 UTC, deltadan commented on deploy/standard-hub/azd-hooks/postprovision.ps1
> +$outputFolderPath = "../standard-hub/config/vpn"
loading from a separate file now

2024-07-25 21:05 UTC, deltadan commented on deploy/standard-hub/infra/core/networking/dnsResolver.bicep
> +func namer(resourceAbbr string, env string, region string, workloadName string, projectId string) string =>
punted

2024-07-25 21:05 UTC, deltadan commented on deploy/standard-hub/azd-hooks/postprovision.ps1
> +# Assuming the XML file is directly inside the expanded folder
good catch... to much troubleshooting. was dup from copy pasta

2024-07-25 21:19 UTC, jamesrcounts requested changes

2024-07-25 21:19 UTC, jamesrcounts commented on deploy/standard-hub/infra/main.bicep
> +param createVpnGateway bool = true
Remove the parameter and the condition that depends on it.

2024-07-25 21:19 UTC, jamesrcounts commented on deploy/standard-hub/azd-hooks/postprovision.ps1
> +    --name $vpnGatewayName
```suggestion
    --name $vpnGatewayName `
   --output tsv
```

2024-07-25 21:19 UTC, jamesrcounts commented on deploy/standard-hub/azd-hooks/postprovision.ps1
> +$vpnClientPackageUrl = $vpnClientPackageUrl -replace '"', ''
```suggestion


```

2024-07-25 21:19 UTC, jamesrcounts commented on deploy/standard-hub/infra/main.bicep
> +output FLLM_PROJECT string = project
```suggestion
output FLLM_PROJECT string = project
output RESOURCE_GROUP_NAME = rg.name
output VPN_GATEWAY_NAME = vpn.name
```

2024-07-26 22:43 UTC, jamesrcounts approved these changes

2024-07-26 22:50 UTC, ciprianjichici approved these changes

2024-07-26 22:50 UTC, merged