Defining a larger VNET and AKS subnets while allowing for IP space to expand
solliancenet/foundationallm pull request #1291
Opened 2024-07-26 22:56 UTC by hatboyzero

# Defining a larger VNET and AKS subnets while allowing for IP space to expand

## Details on the issue fix or feature implementation

Defining a larger VNET and AKS subnets while allowing for IP space to expand

## Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have included inline docs for my changes, where applicable
- [ ]  I have successfully run a local build
- [ ]  I have provided the required update scripts, where applicable
- [ ]  I have updated relevant docs, where applicable

2024-08-05 21:06 UTC, jamesrcounts requested changes

2024-08-05 21:06 UTC, jamesrcounts commented on deploy/standard/infra/networking-rg.bicep
> +var dnsResolverSubnetCidr = cidrSubnet(cidrVnet, 28, 0) // 10.220.134.0/28
Do you know if we need this here?  Shouldn't it be part of the standard hub?

2024-08-06 12:52 UTC, hatboyzero commented on deploy/standard/infra/networking-rg.bicep
> +var dnsResolverSubnetCidr = cidrSubnet(cidrVnet, 28, 0) // 10.220.134.0/28
Removed.

2024-08-06 13:44 UTC, jamesrcounts commented on deploy/standard/infra/modules/vnet-peering.bicep
> +  name: vnetName
This should probably be something like 
```suggestion
  name: 'hub-to-${vnetName}`

```

2024-08-06 13:45 UTC, jamesrcounts approved these changes

2024-08-06 13:49 UTC, hatboyzero commented on deploy/standard/infra/modules/vnet-peering.bicep
> +  name: vnetName
Will address in a later PR.

2024-08-08 17:38 UTC, ciprianjichici approved these changes

2024-08-08 17:38 UTC, merged