Refactor settings management
solliancenet/foundationallm pull request #1293
Opened 2024-07-27 21:13 UTC by ciprianjichici

# {PR title}

## The issue or feature being addressed

Fixes #{bug number} (in this specific format)

## Details on the issue fix or feature implementation

{Detail}

## Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have included inline docs for my changes, where applicable
- [ ]  I have successfully run a local build
- [ ]  I have provided the required update scripts, where applicable
- [ ]  I have updated relevant docs, where applicable

> [!NOTE]
> Instead of adding `X`'s inside the checkboxes you wish to check above, first submit the PR, then check the boxes in the rendered description.

2024-07-28 02:20 UTC, joelhulen commented on src/dotnet/Common/Constants/Data/AppConfiguration.json
> +        "value": "FoundationaLLM (c) 2023",
We should set the year to 2024

2024-07-28 02:20 UTC, joelhulen commented on src/dotnet/Common/Templates/appconfig.template.json
> +            "value": "FoundationaLLM (c) 2023",
We should set the year to 2024

2024-07-28 17:07 UTC, hatboyzero approved these changes

2024-07-28 17:31 UTC, hatboyzero requested changes

2024-07-28 17:31 UTC, hatboyzero commented on src/dotnet/Common/Templates/appconfig.template.json
> +        },
Need to resolve this trailing comma in the JSON dictionary.

2024-07-28 17:40 UTC, hatboyzero requested changes

2024-07-28 17:40 UTC, hatboyzero commented on src/dotnet/Common/Templates/appconfig.template.json
> +            "value": "{\"uri\":\"${env:AZURE_KEY_VAULT_ENDPOINT}secrets/foundationallm-appinsights-connectionstring}\"}",
The trailing `}` in the keyvault URI before the closing quote `\"` is invalid and needs to be removed.  This is occurring in all keyvault URIs generated in this file.

2024-07-28 18:00 UTC, hatboyzero requested changes

2024-07-28 18:32 UTC, ciprianjichici commented on deploy/quick-start/data/resource-provider/FoundationaLLM.Configuration/AzureEventGrid.template copy.json
> +{
That is correct. Renamed the file.

2024-07-28 19:10 UTC, hatboyzero requested changes

2024-07-28 19:10 UTC, hatboyzero commented on src/dotnet/Common/Templates/azure-key-vault-secret-names.json
> +    "FoundationaLLM:APIEndpoints:StateAPI:APIKey": "foundationallm-apinedpoints-stateapi-apikey",
The key name for State API in incorrectly spelled.  It should be `foundationallm-apiendpoints-stateapi-apikey`

2024-07-28 19:41 UTC, hatboyzero requested changes

2024-07-28 19:41 UTC, hatboyzero commented on src/dotnet/Common/Templates/appconfig.template.json
> +            "value": "appinsights-connectionstring",
This value should be a secret like the rest of the service settings around AppInsights connection strings:

`{\"uri\":\"${env:AZURE_KEY_VAULT_ENDPOINT}secrets/foundationallm-apiendpoints-gatekeeperapi-apikey}\"}'

2024-07-28 19:41 UTC, hatboyzero commented on src/dotnet/Common/Templates/appconfig.template.json
> +            "content_type": "",
This value should specify a secret type like the rest of the service settings around AppInsights connection strings:

`application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8`

2024-07-28 19:53 UTC, hatboyzero commented
The following configuration settings are not present in the generated template:
- `FoundationaLLM:ResourceProviders:*:Storage:AccountName`
- `FoundationaLLM:ResourceProviders:*:Storage:AuthenticationType`

2024-07-28 20:01 UTC, hatboyzero commented
DataSourceHub API is still looking for the following config setting:

`FoundationaLLM:APIs:DataSourceHubAPI:AppInsightsConnectionString`

2024-07-28 20:01 UTC, hatboyzero commented
LangChainAPI is still looking for the following config setting:

`FoundationaLLM:APIs:LangChainAPI:AppInsightsConnectionString`

2024-07-28 20:03 UTC, hatboyzero commented
PromptHub API is still looking for the following config setting:

`FoundationaLLM:APIs:PromptHubAPI:AppInsightsConnectionString`

2024-07-28 20:06 UTC, hatboyzero commented
Services are crashing on invalid storage account names and invalid AppInsights connection strings.  I suspect that some of the settings still do not match up with what is expected.

2024-07-29 14:47 UTC, hatboyzero approved these changes

2024-07-29 14:47 UTC, merged