Update Standard to establish a peering to an existing hub VNET
solliancenet/foundationallm pull request #1300
Opened 2024-07-30 01:14 UTC by hatboyzero

# Update Standard to establish a peering to an existing hub VNET

## Details on the issue fix or feature implementation

Update to Standard deployment to establish a peering to an existing hub VNET and link existing private DNS zones to the FoundationaLLM VNET for DNS resolution of resource endpoints.

## Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have included inline docs for my changes, where applicable
- [ ]  I have successfully run a local build
- [ ]  I have provided the required update scripts, where applicable
- [ ]  I have updated relevant docs, where applicable

2024-07-30 02:59 UTC, jamesrcounts requested changes

2024-07-30 02:59 UTC, jamesrcounts commented on deploy/standard/azd-hooks/postprovision.ps1
We still need/want this. Although the VPN solution in our customer hub will work without it, actual customers may need to coordinate with their IT team to configure the proper forwarding, etc. This host file listing can be a useful spec for that request.

2024-07-30 02:59 UTC, jamesrcounts commented on deploy/standard/infra/dns-rg.bicep
>  @description('Create the specified private DNS zones.')
I don't think we need to create these.  They will always be part of the customer hub.

2024-07-30 02:59 UTC, jamesrcounts commented on deploy/standard/infra/main.bicep
> -var useExternalNetworking = !empty(externalNetworkingResourceGroupName)
The feature is meant for when the customer provides the FLLM network, not the hub network; we still need it.

2024-07-30 02:59 UTC, jamesrcounts commented on deploy/standard/infra/main.bicep
> -var resourceGroups = union(defaultResourceGroups, externalResourceGroups)
Since this supports BYO FLLM Network, we still need it

2024-07-30 02:59 UTC, jamesrcounts commented on deploy/standard/infra/main.bicep
> -module dns 'dns-rg.bicep' = if (!useExternalDns) {
Since we will always be using external DNS now, this condition is always false, so my instinct is that the call to the `dns-rg.bicep` template is unnecessary.

2024-07-30 02:59 UTC, jamesrcounts commented on deploy/standard/infra/modules/dns.bicep
>  resource link 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2018-09-01' = {
Ah ok, so you are linking those hub zones to the FLLM network.  Got it.

2024-07-30 02:59 UTC, jamesrcounts commented on deploy/standard/infra/modules/dns.bicep
>  resource link 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2018-09-01' = {
Maybe we should just move the call site for this module to `networking-rg.bicep` and get rid of `dns-rg.bicep`.  Since we aren't managing a DNS resource group anymore, the dns-rg module doesn't make much sense.  TLDR, merge dns-rg into networking-rg.

2024-07-30 03:00 UTC, jamesrcounts commented on deploy/standard/infra/dns-rg.bicep
>  @description('Create the specified private DNS zones.')
In the end I think this file needs to be merged with the networking rg module.  And the description should be updated.

2024-07-30 18:02 UTC, jamesrcounts requested changes

2024-07-30 18:02 UTC, jamesrcounts commented on deploy/standard/infra/main.parameters.json
> +        "value": "${FOUNDATIONALLM_EXT_NET_RG}"
Wasn't there also a value for the network name?

2024-07-30 18:02 UTC, jamesrcounts commented on deploy/standard/infra/networking-rg.bicep
> +param allowedExternalCidr string = '192.168.101.0/28'
Lets remove the default and rely on the one from main.parameters.json

2024-07-31 00:11 UTC, hatboyzero commented on deploy/standard/azd-hooks/postprovision.ps1
Added it back.

2024-07-31 00:12 UTC, hatboyzero commented on deploy/standard/infra/dns-rg.bicep
>  @description('Create the specified private DNS zones.')
Consolidated functionality in the dns module into the networking module.

2024-07-31 00:12 UTC, hatboyzero commented on deploy/standard/infra/modules/dns.bicep
>  resource link 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2018-09-01' = {
Yep, done.

2024-07-31 00:12 UTC, hatboyzero commented on deploy/standard/infra/main.parameters.json
> +        "value": "${FLLM_ALLOWED_CIDR=192.168.101.0/28}"
Done.

2024-07-31 00:12 UTC, hatboyzero commented on deploy/standard/infra/networking-rg.bicep
> +param allowedExternalCidr string = '192.168.101.0/28'
Done.

2024-07-31 13:48 UTC, jamesrcounts approved these changes

2024-08-01 17:20 UTC, ciprianjichici approved these changes

2024-08-01 17:20 UTC, merged