Select Agent dropdown added
solliancenet/foundationallm pull request #288
Opened 2023-11-01 02:50 UTC by CronkCode

- [x]  I started this PR by branching from the head of the default branch
- [x]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [x]  I have included inline docs for my changes, where applicable
- [x]  I have successfully run a local build

2023-11-01 05:42 UTC, joelhulen requested changes

2023-11-01 05:42 UTC, joelhulen commented on src/ui/UserPortal/components/NavBar.vue
> +				{ label: 'FoundationaLLM', value: 'FoundationaLLM' }
Please change this from being a hard-coded list to creating a simple list of agents from the comma-delimited list provided by the `FoundationaLLM:Branding:AllowAgentSelection` configuration value. Please note that this can be one or more agents. If more than one, the agents are separated by commas (eg. `default, SDZWA`). The list only includes the agent names; no separate display name or description provided.

2023-11-01 17:39 UTC, ciprianjichici approved these changes

2023-11-01 17:40 UTC, ciprianjichici approved these changes

2023-11-01 21:32 UTC, joelhulen approved these changes

2023-11-01 22:22 UTC, Sensational-Code approved these changes

2023-11-02 15:18 UTC, ciprianjichici approved these changes

2023-11-02 15:18 UTC, merged