Only allow specific azure keys to be retrieved
solliancenet/foundationallm pull request #297
Opened 2023-11-01 19:42 UTC by Sensational-Code

- [x]  I started this PR by branching from the head of the default branch
- [x]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [x]  I have included inline docs for my changes, where applicable
- [x]  I have successfully run a local build

2023-11-01 21:35 UTC, joelhulen requested changes

2023-11-01 21:35 UTC, joelhulen commented on src/ui/UserPortal/server/api/config/[key].ts
> +];
Please add the following:

'.appconfig.featureflag/FoundationaLLM-AllowAgentHint',
'FoundationaLLM:Branding:AllowAgentSelection'

2023-11-01 21:51 UTC, Sensational-Code commented on src/ui/UserPortal/server/api/config/[key].ts
> +];
@joelhulen Added.

2023-11-02 09:21 UTC, ciprianjichici approved these changes

2023-11-02 15:19 UTC, ciprianjichici approved these changes

2023-11-02 15:37 UTC, ciprianjichici approved these changes

2023-11-02 15:37 UTC, joelhulen approved these changes

2023-11-02 15:37 UTC, merged