Stock Agent, Performance improvements, New Retriever
solliancenet/foundationallm pull request #439
Opened 2024-01-12 20:32 UTC by givenscj

# {PR title}

## The issue or feature being addressed

Fixes #{bug number} (in this specific format)

## Details on the issue fix or feature implementation

{Detail}

## Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have included inline docs for my changes, where applicable
- [ ]  I have successfully run a local build
- [ ]  I have provided the required update scripts, where applicable
- [ ]  I have updated relevant docs, where applicable

> [!NOTE]
> Instead of adding `X`'s inside the checkboxes you wish to check above, first submit the PR, then check the boxes in the rendered description.

2024-01-12 22:01 UTC, codingbandit requested changes

2024-01-12 22:01 UTC, codingbandit commented on src/python/PythonSDK/foundationallm/models/language_models/language_model.py
Again, this looks like it doesn't have the changes made yesterday.

2024-01-12 22:01 UTC, codingbandit commented on src/python/PythonSDK/foundationallm/models/orchestration/completion_request.py
are we using a session id anywhere?

2024-01-12 22:35 UTC, givenscj commented on .vscode/launch.json
We keep going back and forth.  I work off c:/ so I can comment mine or yours, doesn't matter to me.

2024-01-12 22:35 UTC, givenscj commented on .github/workflows/release-docker-image.yml
This was removed.  It came in from previous commits he had in the branch I started with.

2024-01-12 22:36 UTC, givenscj commented on deploy/arm/azureAcaDeploy.json
Same, reverted to one existing.

2024-01-12 22:36 UTC, givenscj commented on src/python/LangChainAPI/app/routers/orchestration.py
it is temporary until we can figure out why its doing that.

2024-01-12 22:37 UTC, givenscj commented on src/python/PythonSDK/foundationallm/models/language_models/language_model.py
added. conflict resolved.  my config base property is in there for my agent code.

2024-01-12 22:57 UTC, codingbandit commented on .vscode/launch.json
That D: path isn't mine either ;p

2024-01-13 02:43 UTC, kylebunting requested changes

2024-01-13 02:43 UTC, kylebunting commented on .vscode/launch.json
Should this file even be part of what gets added to the repo? Seems like it is a candidate for being added to the .gitignore file if we are going to see constant conflicts based on how folks have their environment set up.

2024-01-13 02:43 UTC, kylebunting commented on src/dotnet/AgentFactory/Agents/DefaultAgent.cs
> +                    //TODO
Is there more to do here, or does this need to be deleted?

2024-01-13 02:43 UTC, kylebunting commented on src/dotnet/AgentFactory/Agents/DefaultAgent.cs
> +                                OpenAIEndpoint = dataSource.OpenAIEndpoint,
The OpenAI endpoint and key should really be handled via the LanguageModel object that already has this info, and it should be removed from here.

2024-01-13 02:43 UTC, kylebunting commented on src/dotnet/AgentFactory/Agents/DefaultAgent.cs
> +                                EmbeddingModel = dataSource.EmbeddingModel,
Embedding model info is passed in via the EmbeddingModel object, so that should be used and this should be removed from here.

2024-01-13 02:43 UTC, kylebunting commented on src/dotnet/AgentFactory/Agents/DefaultAgent.cs
> +                                Sources = dataSource.Sources
Shouldn't this be handled via the DataSources object? I'm confused as to what this is doing here.

2024-01-13 02:43 UTC, kylebunting commented on deploy/scripts/BuildPush.ps1
I'm not sure why these files are in here, so cannot really comment or review them.

2024-01-13 02:43 UTC, kylebunting commented on src/dotnet/AgentFactory/Models/Messages/DataSourceHubResponse.cs
> +        public string? OpenAIEndpoint { get; set; }
Same comments as above about the OpenAI and Embeddings models being handled elsewhere.

2024-01-13 02:43 UTC, kylebunting commented on src/dotnet/AgentFactory/Models/Orchestration/DataSourceConfigurations/StockConfiguration.cs
> +        public string? OpenAIEndpoint { get; set; }
Same comment as above.

2024-01-13 02:43 UTC, kylebunting commented on src/dotnet/AgentFactory/Models/Orchestration/Metadata/StockDataSource.cs
> +        /// Blob storage configuration settings.
You should fix your XML inline doc to reflect the Stock, not blob storage, config.

2024-01-13 02:43 UTC, kylebunting commented on src/dotnet/AgentFactory/Services/AgentFactoryService.cs
> +
Remove the extra lines/whitespace?

2024-01-13 02:43 UTC, kylebunting commented on src/dotnet/AgentFactory/Services/AgentFactoryService.cs
> +            if (completionRequest.UserPrompt == "--warmup--")
What purpose does this serve, exactly?

2024-01-13 02:43 UTC, kylebunting commented on src/dotnet/AgentFactory/Services/AgentHubAPIService.cs
Are we introducing a new risk by adding this caching functionality right now?

2024-01-13 02:43 UTC, kylebunting commented on src/dotnet/AgentFactory/Services/DataSourceHubAPIService.cs
Same comment as above about risk with the caching functionality.

2024-01-13 02:43 UTC, kylebunting commented on src/dotnet/AgentFactory/Services/PromptHubAPIService.cs
Same as comments above about caching

2024-01-13 02:43 UTC, kylebunting commented on src/python/IntegrationSDK/foundationallm/integration/config/configuration.py
> +        credential = DefaultAzureCredential( exclude_environment_credential=True)
Why do we need to add this now?

2024-01-13 02:43 UTC, kylebunting commented on src/python/LangChainAPI/app/routers/orchestration.py
> +        #get the orginal request content
This whole block needs to not be here. The Python APIs should be lightweight and not have any logic about a specific agent type in them.

2024-01-13 02:43 UTC, kylebunting commented on src/python/PythonSDK/foundationallm/config/configuration.py
> -            raise e
Shouldn't we still be raising an exception here? What happens in the setting is missing from the local environment variables?

2024-01-13 02:43 UTC, kylebunting commented on src/python/PythonSDK/foundationallm/config/configuration.py
> +        credential = DefaultAzureCredential( exclude_environment_credential=True)
Why is this needed now?

2024-01-13 02:43 UTC, kylebunting commented on src/python/PythonSDK/foundationallm/hubs/agent/agent_hub.py
> -        self.config = Configuration()
You should be able to shorten this to be:

`self.config = config or Configuration()`

2024-01-13 02:43 UTC, kylebunting commented on src/python/PythonSDK/foundationallm/hubs/data_source/data_source_hub.py
> -        self.config = Configuration()
Same comment as above. Make this:

`self.config = config or Configuration()`

2024-01-13 02:43 UTC, kylebunting commented on src/python/PythonSDK/foundationallm/hubs/data_source/data_sources/stock/stock_data_source_metadata.py
> +    open_ai_endpoint: str
Same comments as above for the OpenAI and Embeddings settings coming in with the Language and Embedding models. These values should be pulled from there so we aren't configuring the setting in multiple places.

2024-01-13 02:43 UTC, kylebunting commented on src/python/PythonSDK/foundationallm/hubs/prompt/prompt_hub.py
> +        # initialize config
Make this:

`self.config = config or Configuration()` to replace the if statement.

2024-01-13 02:43 UTC, kylebunting commented on src/python/PythonSDK/foundationallm/langchain/agents/stock_agent.py
> +
The settings for the azure endpoint and key should be pulled from the LanguageModel object.

The embeddings model, should come from the EmbeddingModel.

2024-01-13 02:43 UTC, kylebunting commented on src/python/PythonSDK/foundationallm/langchain/agents/stock_agent.py
> +            local_path = f"c:/temp/{company}"
Is this for local testing? When are we going to have something referencing c:?

2024-01-13 02:43 UTC, kylebunting commented on src/python/PythonSDK/foundationallm/langchain/agents/stock_agent.py
> +    def who_is_question_for(self, question):
We cannot have this in here! This is essentially hardcoding responders, which we don't want.

2024-01-13 02:43 UTC, kylebunting commented on src/python/PythonSDK/foundationallm/langchain/agents/stock_agent.py
> +
These all reference a specific company and doc location. We don't want this in here.

2024-01-13 02:43 UTC, kylebunting commented on src/python/PythonSDK/foundationallm/langchain/agents/stock_agent.py
> +                    index_name="cjg-vector-index",
We probably should not be hardcoding an index name.

2024-01-13 02:43 UTC, kylebunting commented on src/python/PythonSDK/foundationallm/langchain/agents/stock_agent.py
This file has a lot of hardcoded values to things. We need to get that fixed before it can be merged.

2024-01-13 02:43 UTC, kylebunting commented on src/python/PythonSDK/foundationallm/langchain/data_sources/stock/stock_configuration.py
> +    open_ai_endpoint: str
Same comments as above about these values and the Language Model

2024-01-13 02:43 UTC, kylebunting commented on tests/python/PythonSDK.Tests/config/configuration_tests.py
> +        client = AzureAppConfigurationClient(app_config_uri, DefaultAzureCredential( exclude_environment_credential=True))
Why do we need this now?

2024-01-13 03:31 UTC, closed without merging