Vectorization Entra ID Setup
solliancenet/foundationallm pull request #541
Opened 2024-01-31 17:51 UTC by saimachi

# Vectorization Entra ID Setup Document

## The issue or feature being addressed

This document describes how to create two app registrations for the Vectorization API and client.

## Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have included inline docs for my changes, where applicable
- [ ]  I have successfully run a local build
- [ ]  I have provided the required update scripts, where applicable
- [ ]  I have updated relevant docs, where applicable

2024-01-31 19:25 UTC, jamesrcounts reviewed
I think we need to remove instructions about the vectorization client app

2024-01-31 20:09 UTC, jamesrcounts approved these changes
Looks good to me

2024-02-01 13:07 UTC, ciprianjichici reviewed
@jamesrcounts , @joelhulen , @saimachi  if we remove the client app aren't we loosing the ability to get tokens for the Vectorization API later on (when we have moved it to Entra ID auth)?

2024-02-05 15:26 UTC, joelhulen requested changes

2024-02-05 15:26 UTC, joelhulen commented on docs/toc.yml
Let's drop "API" from the authentication setup for Core, Management, and Vectorization, since these include both client and API setup for each category.

2024-02-05 15:26 UTC, joelhulen commented on docs/deployment/authentication/vectorization-authentication-setup-entra.md
> +#### Client secret for the API application
You can remove the client secret section as it's no longer needed. I've already done that with Core and Management.

2024-02-06 11:31 UTC, ciprianjichici approved these changes

2024-02-06 13:54 UTC, joelhulen requested changes

2024-02-06 13:54 UTC, joelhulen commented on docs/deployment/authentication/core-authentication-setup-entra.md
> -# Core API and User Portal authentication setup: Microsoft Entra ID
I only wanted the TOC updated. Please keep the page title as is. Better for searching.

2024-02-06 13:54 UTC, joelhulen commented on docs/deployment/authentication/management-authentication-setup-entra.md
> -# Management API and portal authentication setup: Microsoft Entra ID
I only wanted the TOC updated. Please keep the page title as is. Better for searching.

2024-02-06 14:06 UTC, joelhulen approved these changes

2024-02-06 14:06 UTC, merged