Cj update agent resource provider
solliancenet/foundationallm pull request #557
Opened 2024-02-05 16:03 UTC by ciprianjichici

# {PR title}

## The issue or feature being addressed

Fixes #{bug number} (in this specific format)

## Details on the issue fix or feature implementation

{Detail}

## Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have included inline docs for my changes, where applicable
- [ ]  I have successfully run a local build
- [ ]  I have provided the required update scripts, where applicable
- [ ]  I have updated relevant docs, where applicable

> [!NOTE]
> Instead of adding `X`'s inside the checkboxes you wish to check above, first submit the PR, then check the boxes in the rendered description.

2024-02-10 21:47 UTC, joelhulen requested changes

2024-02-10 21:47 UTC, joelhulen commented on src/dotnet/Common/Models/Events/EventSetEventArgs.cs
> +    /// Delegate
Consider adding a more meaningful description to this delegate. Perhaps something about it being a multicast delegate used by the Event Grid service.

2024-02-10 21:47 UTC, joelhulen commented on src/dotnet/Common/Services/Events/AzureEventGridEventService.cs
> +        private readonly TimeSpan _eventProcessingHeartbeat = TimeSpan.FromMinutes(1);
This value should be injected through configuration. And perhaps use `FromSeconds` for more flexibility.

2024-02-10 21:47 UTC, joelhulen commented on src/dotnet/Common/Services/Events/AzureEventGridEventService.cs
> +                _logger.LogError(ex, "The Azure Event Grid client could not be initialized. The Azure Event Grid event service will not listen for any events.");
Are we logging and swallowing this exception because the Event Grid service is optional? I suppose this makes sense for existing deployments, but do we want to raise the exception in general to ensure we always have this service in a functional state?

2024-02-10 21:47 UTC, joelhulen commented on src/dotnet/Common/Services/Events/AzureEventGridEventService.cs
This class is fairly large, and I want to make sure we're considering separation of concerns. It currently handles multiple responsibilities, such as initializing the Event Grid client, creating/deleting topic subscriptions, and processing events. Consider separating these concerns into separate classes or methods to improve code readability and maintainability.

2024-02-10 21:47 UTC, joelhulen commented on src/dotnet/Common/Services/Storage/BlobStorageService.cs
> +                    _logger.LogError("Could not get a lease for the blob {FilePath} from container {ContainerName}. Reason: unkown.", filePath, containerName);
Typo: "unkown"

Since we are logging the same message as we are raising in the exception, we should use an interpolated string variable and set the value of both the logged message and raised message to that variable. This would also help with inconsistencies such as the typo. The same principle applies to the other code blocks.

2024-02-11 10:58 UTC, ciprianjichici commented on src/dotnet/Common/Services/Storage/BlobStorageService.cs
> +                    _logger.LogError("Could not get a lease for the blob {FilePath} from container {ContainerName}. Reason: unkown.", filePath, containerName);
The choice we have to make is between that and supporting semantic logging (see more at https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-8.0#log-message-template).  The desired approach is to be consistent with the principles of semantic logging (duplicating some part of the message string should be an acceptable price to pay).

2024-02-11 11:07 UTC, ciprianjichici commented on src/dotnet/Common/Models/Events/EventSetEventArgs.cs
> +    /// Delegate
Addressed with the latest commit.

2024-02-11 11:57 UTC, ciprianjichici commented on src/dotnet/Common/Services/Events/AzureEventGridEventService.cs
Factored out the `IAzureResourceManagerService` as this could benefit other components that might need to interact with Azure ARM.
Regarding the initialization of the Event Grid client, all other services using SDK clients are also initializing these. The difference in some cases is that it made sense to provide a base class that performs the validation (e.g., in cases where the same type of service might have different implementations like IBlobStorageService with BlobStorageService and DataLakeStorageService). Since the Event Grid service is very specialized, it is unlikely to have an alternate Azure-based implementation for hit, hence the decision not to factor our a base class.

2024-02-11 12:24 UTC, ciprianjichici commented on src/dotnet/Common/Services/Events/AzureEventGridEventService.cs
> +                _logger.LogError(ex, "The Azure Event Grid client could not be initialized. The Azure Event Grid event service will not listen for any events.");
Reviewed the startup sequence and raised an exception is start fails, delegating the decision to the hosting service. In the case of `CoreAPI`, the Event Service is considered optional, so the exception will not prevent it from starting.

2024-02-11 12:36 UTC, ciprianjichici commented on src/dotnet/Common/Services/Events/AzureEventGridEventService.cs
> +        private readonly TimeSpan _eventProcessingHeartbeat = TimeSpan.FromMinutes(1);
Created a configuration property named `EventProcessingCycleSeconds` and added it to the profile. This is more flexible than adding it to the service settings since it will allow each hosting service to decide on the frequency of pulling events.

2024-02-11 13:31 UTC, joelhulen approved these changes

2024-02-11 20:16 UTC, ciprianjichici commented on src/dotnet/Common/Common.csproj
> +    <Content Remove="C:\Users\ciprian.jichici\.nuget\packages\azure.messaging.eventgrid\4.22.0-beta.1\contentFiles\any\netstandard2.0\EventGridClient.xml" />
Not sure how that ended up in the csproj file. Fixed the issue by manually removing the item group.

2024-02-12 00:08 UTC, joelhulen approved these changes

2024-02-12 00:09 UTC, merged