AZD refactor - Provisioning and Deployment
solliancenet/foundationallm pull request #565
Opened 2024-02-07 00:57 UTC by hatboyzero

# AZD refactor - Provisioning and Deployment

Refactor of the Starter ACA deployment to utilize the Azure Developer Command Line tool for a better end user experience.

## Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have included inline docs for my changes, where applicable
- [ ]  I have successfully run a local build
- [ ]  I have provided the required update scripts, where applicable
- [ ]  I have updated relevant docs, where applicable

2024-02-07 14:54 UTC, jamesrcounts requested changes
There is a better way i think to create short names using uniquestring instead of truncation.  

Also the docs need to be updated don't they?  Do we need `Unified-Deploy.ps1` anymore. It looks completely broken now that the JSON files are gone.

2024-02-07 14:54 UTC, jamesrcounts commented on deploy/starter/infra/app/acaService.bicep
> +var truncatedAppName = substring(formattedAppName, 0, min(length(formattedAppName), 32))
We need not to truncate anymore.  Lets use `uniquestring`.

2024-02-07 14:55 UTC, jamesrcounts commented on deploy/starter/infra/app/acaService.bicep
> +var truncatedAppName = substring(formattedAppName, 0, min(length(formattedAppName), 32))
example

```
// Generate a unique token to be used in naming resources.
// Remove linter suppression after using.
#disable-next-line no-unused-vars
var resourceToken = toLower(uniqueString(subscription().id, environmentName, location, instance))
```

2024-02-09 21:48 UTC, ciprianjichici approved these changes

2024-02-09 21:53 UTC, ciprianjichici approved these changes

2024-02-09 21:59 UTC, ciprianjichici approved these changes

2024-02-09 21:59 UTC, hatboyzero commented on deploy/starter/infra/app/acaService.bicep
> +var truncatedAppName = substring(formattedAppName, 0, min(length(formattedAppName), 32))
Using uniquestring() in resource suffix generation.

2024-02-09 22:17 UTC, ciprianjichici approved these changes

2024-02-09 22:17 UTC, jamesrcounts approved these changes

2024-02-09 22:17 UTC, merged