Release 0.4.0: Final Docs Passthrough
solliancenet/foundationallm pull request #676
Opened 2024-02-27 11:55 UTC by saimachi

# Release 0.4.0: Final Docs Passthrough

## The issue or feature being addressed

This PR includes fixes for the Vectorization profile list (casing, redundancy) and the overwritten AZD deployment instructions.

## Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have included inline docs for my changes, where applicable
- [ ]  I have successfully run a local build
- [ ]  I have provided the required update scripts, where applicable
- [ ]  I have updated relevant docs, where applicable

2024-02-27 17:04 UTC, joelhulen requested changes

2024-02-27 17:04 UTC, joelhulen commented on docs/deployment/deployment-starter.md
> +2. From a PowerShell or bash prompt, execute the following to clone the latest release from the FLLM repository:
Please either spell out "FoundationaLLM" here or add (FLLM) after the first mention of "FoundationaLLM" at the top of the document.

2024-02-28 15:14 UTC, ciprianjichici approved these changes

2024-02-28 16:59 UTC, joelhulen approved these changes

2024-02-28 16:59 UTC, merged