AKS Forwarding Documentation
solliancenet/foundationallm pull request #695
Opened 2024-03-01 15:27 UTC by saimachi

# AKS Forwarding Documentation

## The issue or feature being addressed

This PR includes a document demonstrating how to use the AKS forwarding script currently in main.

## Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have included inline docs for my changes, where applicable
- [ ]  I have successfully run a local build
- [ ]  I have provided the required update scripts, where applicable
- [ ]  I have updated relevant docs, where applicable

2024-03-01 15:31 UTC, joelhulen requested changes

2024-03-01 15:31 UTC, joelhulen commented on docs/development/calling-apis/standard-deployment-local-api-access.md
> +You will need to rerun the script if you restart any nodes while the script is running.
Can you make this:

> [!NOTE]
> You will need to rerun the script if you restart any nodes while the script is running.

2024-03-01 15:31 UTC, joelhulen commented on docs/development/calling-apis/standard-deployment-local-api-access.md
> +
Add an `az login` step before the `az aks get-credentials` step.

2024-03-01 15:56 UTC, joelhulen approved these changes

2024-03-02 17:19 UTC, ciprianjichici approved these changes

2024-03-02 17:19 UTC, merged