Adding storage account and container app instance for supporting Authorization API requirements
solliancenet/foundationallm pull request #710
Opened 2024-03-05 23:11 UTC by hatboyzero

# Adding storage account and container app instance for supporting Authorization API requirements

## Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have included inline docs for my changes, where applicable
- [ ]  I have successfully run a local build
- [ ]  I have provided the required update scripts, where applicable
- [ ]  I have updated relevant docs, where applicable

2024-03-06 18:41 UTC, jamesrcounts requested changes

2024-03-06 18:41 UTC, jamesrcounts commented on deploy/starter/infra/app/authAcaService.bicep
> +resource containerAppsEnvironment 'Microsoft.App/managedEnvironments@2023-04-01-preview' existing = {
@ciprianjichici, based on your comments about wanting to isolate this as much as possible, I'm wondering if you think it is ok for it to share the same Container App Environment.

2024-03-06 18:41 UTC, jamesrcounts commented on deploy/starter/infra/app/authAcaService.bicep
> +resource acrPullRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
Can we remove the ACR and therefore the need for this role?

2024-03-06 18:41 UTC, jamesrcounts commented on deploy/starter/infra/app/authAcaService.bicep
> +resource keyvault 'Microsoft.KeyVault/vaults@2023-07-01' existing = {
Sharing a key vault.  Is this the proper isolation level?

2024-03-06 18:41 UTC, jamesrcounts commented on deploy/starter/infra/main.bicep
> +  scope: rg
We discussed putting this in a separate RG; was that not feasible?

2024-03-06 19:00 UTC, ciprianjichici commented on deploy/starter/infra/app/authAcaService.bicep
> +resource containerAppsEnvironment 'Microsoft.App/managedEnvironments@2023-04-01-preview' existing = {
Depends on the implications, but would be good to isolate as much as possible

2024-03-06 19:01 UTC, ciprianjichici commented on deploy/starter/infra/app/authAcaService.bicep
> +resource acrPullRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
Why do we even need an ACR?

2024-03-06 19:01 UTC, ciprianjichici commented on deploy/starter/infra/main.bicep
> +  scope: rg
It is, as far as I am concerned

2024-03-06 19:03 UTC, jamesrcounts commented on deploy/starter/infra/app/authAcaService.bicep
> +resource acrPullRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
That is basically my question.

2024-03-06 19:04 UTC, jamesrcounts commented on deploy/starter/infra/app/authAcaService.bicep
> +resource containerAppsEnvironment 'Microsoft.App/managedEnvironments@2023-04-01-preview' existing = {
Operating cost and deployment time. We already know how to make them, so it sounds like a good idea.  I don't think it will change our ability to call it from other services.

2024-03-06 19:05 UTC, jamesrcounts commented on deploy/starter/infra/app/authAcaService.bicep
> +resource keyvault 'Microsoft.KeyVault/vaults@2023-07-01' existing = {
This could be a side effect of the storage module wanting to put its connection string in the key vault, but if so, we should make that optional.  Unless there is a reason to do it @hatboyzero?

2024-03-06 22:32 UTC, ciprianjichici commented on deploy/starter/infra/app/authAcaService.bicep
> +resource containerAppsEnvironment 'Microsoft.App/managedEnvironments@2023-04-01-preview' existing = {
If it adds to the deployment time, I'd say let's use the same environment.

2024-03-06 22:33 UTC, ciprianjichici commented on deploy/starter/infra/app/authAcaService.bicep
> +resource keyvault 'Microsoft.KeyVault/vaults@2023-07-01' existing = {
If we end up using a separate RG (which we want) then it would also make sense to use a dedicated KV. This way we can avoid injecting the environment variables. We will need to restrict any access to that KV to the managed identity of the authorization service.

2024-03-06 23:47 UTC, jamesrcounts commented on deploy/starter/infra/app/authAcaService.bicep
> +resource keyvault 'Microsoft.KeyVault/vaults@2023-07-01' existing = {
Seems like KV is needed, so lets make a dedicated one.

2024-03-07 18:00 UTC, hatboyzero commented on deploy/starter/infra/app/authAcaService.bicep
> +resource keyvault 'Microsoft.KeyVault/vaults@2023-07-01' existing = {
Dedicated KV added and provisioned in auth RG.

2024-03-07 18:00 UTC, hatboyzero commented on deploy/starter/infra/main.bicep
> +  scope: rg
Authorization store moved to auth RG.

2024-03-07 18:00 UTC, hatboyzero commented on deploy/starter/infra/app/authAcaService.bicep
> +resource acrPullRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
Container registry and references to it removed from bicep templates

2024-03-07 18:07 UTC, jamesrcounts approved these changes

2024-03-10 18:54 UTC, ciprianjichici approved these changes

2024-03-10 18:54 UTC, merged