Adding CosmosDB SQL role assignments to Core API and Core Worker MSIs
solliancenet/foundationallm pull request #719
Opened 2024-03-08 19:53 UTC by hatboyzero

# Adding CosmosDB SQL role assignments to Core API and Core Worker MSIs

## Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have included inline docs for my changes, where applicable
- [ ]  I have successfully run a local build
- [ ]  I have provided the required update scripts, where applicable
- [ ]  I have updated relevant docs, where applicable

2024-03-08 20:05 UTC, jamesrcounts requested changes

2024-03-08 20:05 UTC, jamesrcounts commented on deploy/starter/infra/main.bicep
> +resource cosmosDbRef 'Microsoft.DocumentDB/databaseAccounts@2023-11-15' existing = {
This does not appear to be used

2024-03-08 20:05 UTC, jamesrcounts commented on deploy/starter/infra/shared/sqlRoleAssignments.bicep
> +      roleDefinitionId: '/${subscription().id}/resourceGroups/${resourceGroup().name}/providers/Microsoft.DocumentDB/databaseAccounts/${cosmosDb.name}/sqlRoleDefinitions/${roleAssignmentToCreate.role
Use resource id function: https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-resource#resourceid

Not tested:
```suggestion
       roleDefinitionId: resourceId('Microsoft.DocumentDB/databaseAccounts', cosmosDb.name, 'sqlRoleDefinition', roleAssignmentToCreate.roleDefinitionId)
```

2024-03-11 14:56 UTC, hatboyzero commented on deploy/starter/infra/shared/sqlRoleAssignments.bicep
> +      roleDefinitionId: '/${subscription().id}/resourceGroups/${resourceGroup().name}/providers/Microsoft.DocumentDB/databaseAccounts/${cosmosDb.name}/sqlRoleDefinitions/${roleAssignmentToCreate.role
I attempted to test after making this change and was met with the following error:

```
Deployment Error Details:
InvalidTemplate: Unable to process template language expressions for resource '/subscriptions/0a03d4f9-c6e4-4ee1-87fb-e2005d2c213d/resourceGroups/rg-fllm-0-4-0-aca/providers/Microsoft.DocumentDB/databaseAccounts/cosmos-pus65k7rkrjdw/sqlRoleAssignments/be05dc2f-03fd-521f-90fb-f2da08194b29' at line '1' and column '1223'. 'Unable to evaluate template language function 'resourceId': the type 'Microsoft.DocumentDB/databaseAccounts' requires '1' resource name argument(s). Please see https://aka.ms/arm-resource-functions/#resourceid for usage details.'
InvalidTemplate: Unable to process template language expressions for resource '/subscriptions/0a03d4f9-c6e4-4ee1-87fb-e2005d2c213d/resourceGroups/rg-fllm-0-4-0-aca/providers/Microsoft.DocumentDB/databaseAccounts/cosmos-pus65k7rkrjdw/sqlRoleAssignments/2462ae01-8939-5305-8247-e959ffa36fe9' at line '1' and column '1223'. 'Unable to evaluate template language function 'resourceId': the type 'Microsoft.DocumentDB/databaseAccounts' requires '1' resource name argument(s). Please see https://aka.ms/arm-resource-functions/#resourceid for usage details.'
```

I agree that this should be done the "right" way, but this isn't it.  Will investigate further after resolving other more pressing tasks.

2024-03-22 15:25 UTC, ciprianjichici approved these changes

2024-03-22 15:28 UTC, ciprianjichici approved these changes

2024-03-22 15:28 UTC, merged