050 docs updates
solliancenet/foundationallm pull request #831
Opened 2024-04-01 16:42 UTC by TheTrainingBoss

# 050 docs updates

## Details on the issue fix or feature implementation

Documentation Updates

## Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have included inline docs for my changes, where applicable
- [ ]  I have successfully run a local build
- [ ]  I have provided the required update scripts, where applicable
- [ ]  I have updated relevant docs, where applicable

> [!NOTE]
> Instead of adding `X`'s inside the checkboxes you wish to check above, first submit the PR, then check the boxes in the rendered description.

2024-04-01 17:05 UTC, saimachi requested changes

2024-04-01 17:05 UTC, saimachi commented on docs/deployment/changes-050.md
Correct the casing of `Admin_GROUP_OBJECT_ID` on line 105. Explicitly specify that this refers to Entra groups.

2024-04-01 17:05 UTC, saimachi commented on docs/toc.yml
I would remove the Vectorization Entra ID setup document and Table of Contents entry, given that Vectorization won't be using Entra in the future.

2024-04-01 17:33 UTC, TheTrainingBoss commented on docs/deployment/authentication-authorization/management-authentication-setup-entra.md
It needs to be done

2024-04-01 17:34 UTC, TheTrainingBoss commented on docs/deployment/authentication-authorization/authorization-setup-entra.md
what is "dedent"?  do you mean "delete"

2024-04-15 14:23 UTC, ciprianjichici approved these changes

2024-04-15 15:34 UTC, ciprianjichici approved these changes

2024-04-15 15:37 UTC, joelhulen approved these changes

2024-04-15 15:38 UTC, merged