Resolving issues with Quick Start deployment in `main`
solliancenet/foundationallm pull request #878
Opened 2024-04-18 17:15 UTC by hatboyzero

# Resolving issues with Quick Start deployment in `main`

- Verfied that the principal id for the Core API role assignment is correct
- Removed Gatekeeper Integration API reference in Quick-Start deployment 
- Added back the missing config template JSON for the Management API
- Finished renaming the Agent Factory API assets and artifacts that were otherwise breaking deployment

## Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have included inline docs for my changes, where applicable
- [ ]  I have successfully run a local build
- [ ]  I have provided the required update scripts, where applicable
- [ ]  I have updated relevant docs, where applicable

2024-04-18 17:47 UTC, joelhulen requested changes

2024-04-18 17:47 UTC, joelhulen commented on docs/release-notes/breaking-changes.md
Please revert the renaming in this file.

2024-04-18 22:06 UTC, hatboyzero commented on docs/release-notes/breaking-changes.md
Reverted.

2024-04-18 22:24 UTC, joelhulen approved these changes

2024-04-22 15:45 UTC, ciprianjichici approved these changes

2024-04-22 15:45 UTC, merged