Update Knowledge Management Documentation
solliancenet/foundationallm pull request #930
Opened 2024-05-02 18:27 UTC by saimachi

# Update Knowledge Management Documentation

## Details on the issue fix or feature implementation

This PR updates the Knowledge Management agent setup guide, reflecting recent schema changes.

## Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have included inline docs for my changes, where applicable
- [ ]  I have successfully run a local build
- [ ]  I have provided the required update scripts, where applicable
- [ ]  I have updated relevant docs, where applicable

2024-05-02 19:06 UTC, kylebunting requested changes

2024-05-02 20:13 UTC, saimachi commented on docs/setup-guides/agents/knowledge-management-agent.md
>  | `language_model` | The language model configuration. This sample demonstrates the usage of the Azure OpenAI language model. |
I added a deprecation notice.

2024-05-02 20:29 UTC, kylebunting requested changes

2024-05-02 20:29 UTC, kylebunting commented on docs/setup-guides/agents/knowledge-management-agent.md
> +| `vectorization.data_source_object_id` | The object ID of the Data Source resource. |
Here, I would reword this comment slightly. Maybe refer to the agent as a Knowledge Management agent without an inline context versus the "non-Inline Context Knowledge Management" agent.

2024-05-02 20:39 UTC, kylebunting approved these changes

2024-05-02 20:50 UTC, joelhulen approved these changes

2024-05-03 08:58 UTC, ciprianjichici commented on docs/setup-guides/agents/knowledge-management-agent.md
The agent structure is not correct, the `vectorization` section is missing multiple properties (see `Common/Models/Agent/KnowledgeManagementAgent.cs`.

2024-05-03 14:35 UTC, ciprianjichici approved these changes

2024-05-03 14:35 UTC, merged